[gunicorn]
ip = "0.0.0.0"
port = 80
timeout = 1800
workers = 1
worker_class = "custom_uvicorn_worker.CustomUvicornWorker"

[log]
file = "log"
level = "INFO"

[model]
detection_size = [2560, 1280]
detection_threshold = 0.5
file = "det_10g.onnx"
gpu = false

[slack]
token = ""
channel_id = ""

[uvicorn]
timeout_keep_alive = 120
