[gunicorn]
ip = "0.0.0.0"
port = 80
timeout = 1800
workers = 1
worker_class = "custom_uvicorn_worker.CustomUvicornWorker"

[log]
file = "log"
level = "INFO"

[slack]
token = ""
channel_id = ""

[uvicorn]
timeout_keep_alive = 120
